# Generated by Django 3.1.3 on 2021-01-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='readnum',
            table='readnum',
        ),
    ]
