# Generated by Django 3.1.3 on 2021-01-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_message_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
    ]
