# Generated by Django 3.1.3 on 2021-01-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210118_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
