# Generated by Django 3.1.3 on 2021-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210125_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments_num',
            field=models.IntegerField(default=0),
        ),
    ]
