# Generated by Django 3.1.3 on 2021-01-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_resgistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_board',
            name='message',
        ),
    ]
