# Generated by Django 3.1.3 on 2021-01-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_message_board_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_board',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='message_board',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message_board',
            name='message_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
