# Generated by Django 3.1.3 on 2021-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210126_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_board',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message_board',
            name='message_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
