# Generated by Django 3.1.3 on 2021-01-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210126_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='user_likes',
            field=models.IntegerField(default=0),
        ),
    ]
