# Generated by Django 3.1.3 on 2021-01-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time']},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
